# typed: strict
# frozen_string_literal: true

# Generated by scripts/homebrew.ts. Do not edit the generated copy in the tap.
class Second < Formula
  desc "Second companion command-line client"
  homepage "https://2nd.thedevdavid.com"
  version "1.15.0"

  on_macos do
    on_arm do
      url "https://github.com/thedevdavid/homebrew-tap/releases/download/second-v#{version}/second-bun-darwin-arm64.tar.gz"
      sha256 "74baf9802537d8f51df847346eb4db343dee522d722732a936f5ca2428c3f738"
    end
    on_intel do
      url "https://github.com/thedevdavid/homebrew-tap/releases/download/second-v#{version}/second-bun-darwin-x64.tar.gz"
      sha256 "96444bbaf19e27202e0a6074b5ae4d335777202b2299239b284de27410d1bb77"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/thedevdavid/homebrew-tap/releases/download/second-v#{version}/second-bun-linux-arm64.tar.gz"
      sha256 "595b4afebbc6769d54f5f129f56e34c2778717883ccb24679f2f9afdc3e6dbaf"
    end
    on_intel do
      url "https://github.com/thedevdavid/homebrew-tap/releases/download/second-v#{version}/second-bun-linux-x64.tar.gz"
      sha256 "696d0c2aed2e693bd3cceaff6f9f997e78bf68ba91dc5a56536552eed6721635"
    end
  end

  def install
    binary = Dir["second-bun-*"].fetch(0) { raise "second binary not found in archive" }
    bin.install binary => "second"
  end

  test do
    assert_match "capture", shell_output("#{bin}/second --help")
  end
end
