# typed: strict
# frozen_string_literal: true

# Generated by scripts/homebrew.ts. Do not edit the generated copy in the tap.
class Second < Formula
  desc "Second companion command-line client"
  homepage "https://2nd.thedevdavid.com"
  version "1.19.4"

  on_macos do
    on_arm do
      url "https://github.com/thedevdavid/homebrew-tap/releases/download/second-v#{version}/second-bun-darwin-arm64.tar.gz"
      sha256 "e2bb4a568eb886402929c22cccf2945112765f9d1b6c878ad0da086b06af776a"
    end
    on_intel do
      url "https://github.com/thedevdavid/homebrew-tap/releases/download/second-v#{version}/second-bun-darwin-x64.tar.gz"
      sha256 "e910ccf794ef93cd882a8796771d53f2e397913f020010580323836a5efb793d"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/thedevdavid/homebrew-tap/releases/download/second-v#{version}/second-bun-linux-arm64.tar.gz"
      sha256 "75826db0fe26258c6801061c01df3958a0652a0018c265ff5e3e5f6045433f8b"
    end
    on_intel do
      url "https://github.com/thedevdavid/homebrew-tap/releases/download/second-v#{version}/second-bun-linux-x64.tar.gz"
      sha256 "93293622ac3ce6944c91b52eee1cc48b5389ba8e3b23975e6d626856ffe88571"
    end
  end

  def install
    binary = Dir["second-bun-*"].fetch(0) { raise "second binary not found in archive" }
    bin.install binary => "second"
  end

  test do
    assert_match "capture", shell_output("#{bin}/second --help")
  end
end
