# typed: strict
# frozen_string_literal: true

# Generated by scripts/homebrew.ts. Do not edit the generated copy in the tap.
class Second < Formula
  desc "Second companion command-line client"
  homepage "https://2nd.thedevdavid.com"
  version "2.4.0"

  on_macos do
    on_arm do
      url "https://github.com/thedevdavid/homebrew-tap/releases/download/second-v#{version}/second-bun-darwin-arm64.tar.gz"
      sha256 "ad03dba18bf0a0dfe5c88474318dd87a9d97165b38a7af996d130d2a83f39ca7"
    end
    on_intel do
      url "https://github.com/thedevdavid/homebrew-tap/releases/download/second-v#{version}/second-bun-darwin-x64.tar.gz"
      sha256 "f2194cdad6cfa03cf03c6439c521ccb44262ba32166cc73c558c489fb070d992"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/thedevdavid/homebrew-tap/releases/download/second-v#{version}/second-bun-linux-arm64.tar.gz"
      sha256 "53ee9d0b9e54a91d00484e48ca3a36a659db387d11d84bd348c446c66a2fc838"
    end
    on_intel do
      url "https://github.com/thedevdavid/homebrew-tap/releases/download/second-v#{version}/second-bun-linux-x64.tar.gz"
      sha256 "f7ff6d084d07e156be45fa0118313cfc5ef585c1a4404d3814467ac57bfb7092"
    end
  end

  def install
    binary = Dir["second-bun-*"].fetch(0) { raise "second binary not found in archive" }
    bin.install binary => "second"
  end

  test do
    assert_match "capture", shell_output("#{bin}/second --help")
  end
end
